//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶聯絡人
    {
        //Required：檢查必填
        //StringLength：檢查字串長度
        //DisplayFormat：設定小數點數為0位
        [Required(ErrorMessage = "{0}不可為空！")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "只能輸入數字！")]
        public int Id { get; set; }
        [Required(ErrorMessage = "{0}不可為空！")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "只能輸入數字！")]
        public int 客戶Id { get; set; }
        [Required(ErrorMessage = "{0}不可為空！")]
        [StringLength(50, ErrorMessage = "{0}長度不可超過{1}個字元！")]
        public string 職稱 { get; set; }
        [Required(ErrorMessage = "{0}不可為空！")]
        [StringLength(50, ErrorMessage = "{0}長度不可超過{1}個字元！")]
        public string 姓名 { get; set; }
        [Required(ErrorMessage = "{0}不可為空！")]
        [StringLength(250, ErrorMessage = "{0}長度不可超過{1}個字元！")]
        [EmailAddress(ErrorMessage = "請輸入正確的電子郵件位址！")]
        public string Email { get; set; }
        [StringLength(50, ErrorMessage = "{0}長度不可超過{1}個字元！")]
        //[DataType(DataType.PhoneNumber, ErrorMessage = "請輸入正確的手機號碼！")] 無效
        //[Phone(ErrorMessage = "請輸入正確的手機號碼！")] 無效
        public string 手機 { get; set; }
        [StringLength(50, ErrorMessage = "{0}長度不可超過{1}個字元！")]
        public string 電話 { get; set; }
        public bool 是否已刪除 { get; set; }

        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
